/* SPDX-License-Identifier: Apache-2.0 */
/** Build the fixed runtime program used by every deterministic Salesforce profile. */
import type { CanvasProgramPayload } from "./types.ts";

export function buildCanvasProgram(payload: CanvasProgramPayload): string {
  const encoded = JSON.stringify(payload).replace(/</g, "\\u003c");
  return `
const payload=${encoded}
const {AssetRecordType,PageRecordType,createShapeId,toRichText,getArrowInfo}=await import('tldraw')
const FAMILY=payload.family
const counters={created:0,updated:0,deleted:0}
function hash(value){let h=2166136261;for(let i=0;i<value.length;i++){h^=value.charCodeAt(i);h=Math.imul(h,16777619)}return (h>>>0).toString(36)}
function slug(value){return String(value).toLowerCase().replace(/[^a-z0-9_-]+/g,'-').replace(/^-+|-+$/g,'').slice(0,46)}
function sid(key){const scoped=payload.pageName+'|'+key;return createShapeId('sf-tldraw-'+slug(payload.pageName)+'-'+slug(key)+'-'+hash(scoped))}
function managed(key,semanticId,role,extra={}){return{...extra,sfTldraw:{managed:true,schemaVersion:1,family:FAMILY,key,semanticId,role}}}
function keyOf(shape){return shape?.meta?.sfTldraw?.key}
function geo(id,x,y,w,h,color='grey',fill='none',dash='solid',label='',meta={},geoType='rectangle'){return{id,type:'geo',x,y,meta,props:{geo:geoType,w,h,color,fill,dash,size:'s',font:'sans',align:'middle',verticalAlign:'middle',richText:toRichText(label)}}}
function text(id,x,y,w,label,size='s',align='start',meta={},color='black'){return{id,type:'text',x,y,meta,props:{color,size,font:'sans',textAlign:align,w,richText:toRichText(label),scale:1,autoSize:false}}}
function image(id,x,y,w,h,assetId,altText,rotation=0,meta={}){return{id,type:'image',x,y,rotation,meta,props:{w,h,playing:false,url:'',assetId,crop:null,flipX:false,flipY:false,altText}}}
function sequenceColorFor(node){if(node.kind==='salesforce'){const index=payload.nodes.filter(item=>item.kind==='salesforce').findIndex(item=>item.id===node.id);return['yellow','light-green','light-blue','orange'][Math.max(0,index)%4]}return node.kind==='data_store'?'light-green':node.kind==='integration'?'light-violet':node.kind==='user'?'light-blue':node.kind==='external'?'light-blue':'grey'}
function colorFor(node){if(FAMILY==='sequence')return sequenceColorFor(node);if(FAMILY!=='data_model')return node.kind==='salesforce'?'blue':node.kind==='data_store'?'green':node.kind==='external'?'grey':'violet';return node.family==='custom'?'green':node.family==='external'?'grey':node.family==='special'?'violet':'blue'}
function fillFor(node){if(FAMILY==='sequence')return'solid';return node.family==='external'?'pattern':'semi'}
function sequenceLineStyleCount(){return new Set((payload.sequenceInteractions??[]).map(item=>item.meaning==='response'?'dashed':item.meaning==='async'?'dotted':'solid')).size}
function wantedKeys(){const keys=new Set(['header:title','header:scope','header:grounding']);if(FAMILY!=='sequence'||sequenceLineStyleCount()>1)keys.add('header:legend');for(const node of payload.nodes){for(const role of ['group','card','label'])keys.add('node:'+node.id+':'+role);if(node.iconTileAssetId)keys.add('node:'+node.id+':tile');if(node.iconAssetId)keys.add('node:'+node.id+':icon');if(node.apiName)keys.add('node:'+node.id+':api');if(node.subtitle)keys.add('node:'+node.id+':subtitle');if(node.keyFields?.length)keys.add('node:'+node.id+':keys');if(node.boundary)keys.add('node:'+node.id+':boundary');if(FAMILY==='sequence')keys.add('node:'+node.id+':lifeline');for(let i=0;i<(node.observations?.length??0);i++)keys.add('node:'+node.id+':observation:'+i)}for(const edge of payload.edges){for(const role of ['arrow','label'])keys.add('edge:'+edge.id+':'+role);if(FAMILY==='sequence')keys.add('edge:'+edge.id+':label-bg');if(FAMILY==='data_model'){keys.add('edge:'+edge.id+':from-marker');keys.add('edge:'+edge.id+':to-marker')}}for(const interaction of payload.sequenceInteractions??[]){keys.add('edge:'+interaction.id+':from-anchor');keys.add('edge:'+interaction.id+':to-anchor')}for(const activation of payload.sequenceActivations??[])keys.add('node:'+activation.participantId+':activation:'+activation.id);return keys}
const existingPage=editor.getPages().find(page=>page.name===payload.pageName)
const pageId=existingPage?.id??PageRecordType.createId('sf-tldraw-page-'+hash(payload.pageName))
if(!existingPage)editor.createPage({id:pageId,name:payload.pageName})
editor.setCurrentPage(pageId)
let pageShapes=editor.getCurrentPageShapes()
const wanted=wantedKeys()
const allManagedShapes=pageShapes.filter(shape=>shape.meta?.sfTldraw?.managed===true)
const managedShapes=allManagedShapes.filter(shape=>shape.meta?.sfTldraw?.family===FAMILY)
const remove=payload.renderMode==='replace'?allManagedShapes:managedShapes.filter(shape=>!wanted.has(keyOf(shape)))
if(remove.length){editor.deleteShapes(remove.map(shape=>shape.id));counters.deleted+=remove.length}
const assetRecords=payload.assets.filter(asset=>!editor.getAsset(AssetRecordType.createId(asset.id))).map(asset=>({id:AssetRecordType.createId(asset.id),typeName:'asset',type:'image',props:{name:asset.name,src:asset.src,w:asset.width,h:asset.height,mimeType:asset.mimeType,isAnimated:false},meta:{sfTldraw:{managed:true,schemaVersion:1},...(asset.attribution?{attribution:asset.attribution}:{})}}))
if(assetRecords.length)editor.createAssets(assetRecords)
function upsert(shape,{position='managed'}={}){const current=editor.getShape(shape.id);if(!current){editor.createShape(shape);counters.created++;return true}if(current.type!==shape.type){editor.deleteShapes([current.id]);editor.createShape(shape);counters.deleted++;counters.created++;return true}const update={id:shape.id,type:shape.type,props:shape.props,meta:shape.meta};if(position==='always'||(position==='managed'&&payload.renderMode!=='preserve')){update.x=shape.x;update.y=shape.y;if(shape.rotation!==undefined)update.rotation=shape.rotation}editor.updateShape(update);counters.updated++;return false}
function moveShapeToPage(id,x,y){const bounds=editor.getShapePageBounds(id);const dx=x-bounds.x,dy=y-bounds.y;if(Math.abs(dx)>0.01||Math.abs(dy)>0.01)helpers.translateShapes([id],dx,dy)}
const maxX=Math.max(1200,...payload.nodes.map(node=>node.x+node.w))+100
const legend=FAMILY==='data_model'?'bar/crow foot = declared cardinality · LK = lookup · MD = master-detail':FAMILY==='architecture'?'solid = direction · dashed = async/batch · dotted = dependency':'step number precedes message · solid = request/event · dashed = response · dotted = async'
if(FAMILY==='sequence'){
 upsert(text(sid('header:title'),80,20,maxX-160,payload.title.toUpperCase(),'xl','start',managed('header:title','header','title'),'grey'))
 upsert(text(sid('header:scope'),80,105,Math.max(500,maxX-160),'Scope · '+payload.scope,'m','start',managed('header:scope','header','scope')))
 upsert(text(sid('header:grounding'),80,153,Math.max(500,maxX-160),payload.groundingText,'s','start',managed('header:grounding','header','grounding'),'grey'))
 if(sequenceLineStyleCount()>1)upsert(text(sid('header:legend'),80,199,Math.max(500,maxX-160),legend,'s','start',managed('header:legend','header','legend'),'grey'))
}else{
 upsert(geo(sid('header:title'),40,20,maxX-80,78,'blue','none','solid',payload.title.toUpperCase(),managed('header:title','header','title')))
 upsert(text(sid('header:scope'),80,116,Math.max(500,maxX-650),'Scope · '+payload.scope,'m','start',managed('header:scope','header','scope')))
 upsert(text(sid('header:grounding'),80,164,Math.max(500,maxX-160),payload.groundingText,'s','start',managed('header:grounding','header','grounding')))
 upsert(text(sid('header:legend'),80,214,Math.max(500,maxX-160),legend,'s','start',managed('header:legend','header','legend')))
}
const cardBackgrounds=new Map(),nodeGroups=new Map(),foreground=[]
for(const node of payload.nodes){
 const prefix='node:'+node.id+':'
 const ids={group:sid(prefix+'group'),card:sid(prefix+'card'),tile:sid(prefix+'tile'),icon:sid(prefix+'icon'),label:sid(prefix+'label'),api:sid(prefix+'api'),subtitle:sid(prefix+'subtitle'),keys:sid(prefix+'keys'),boundary:sid(prefix+'boundary')}
 const groupExists=!!editor.getShape(ids.group)
 const childIds=[]
 const cardFill=FAMILY==='architecture'?'none':fillFor(node)
 upsert(geo(ids.card,node.x,node.y,node.w,node.h,colorFor(node),cardFill,'solid','',managed(prefix+'card',node.id,'card')),{position:groupExists?'never':'managed'});childIds.push(ids.card);cardBackgrounds.set(node.id,ids.card)
 if(FAMILY==='sequence'){
  const cardBounds=editor.getShapePageBounds(ids.card),hasVisual=Boolean(node.iconTileAssetId&&node.iconAssetId),iconSize=44,iconX=cardBounds.x+18,iconY=cardBounds.y+(cardBounds.h-iconSize)/2
  if(node.iconTileAssetId){upsert(image(ids.tile,iconX,iconY,iconSize,iconSize,AssetRecordType.createId(node.iconTileAssetId),node.label+' icon background',0,managed(prefix+'tile',node.id,'icon-tile')),{position:groupExists?'never':'managed'});if(groupExists)moveShapeToPage(ids.tile,iconX,iconY);childIds.push(ids.tile);foreground.push(ids.tile)}
  if(node.iconAssetId){upsert(image(ids.icon,iconX,iconY,iconSize,iconSize,AssetRecordType.createId(node.iconAssetId),node.label+' SLDS icon',0,managed(prefix+'icon',node.id,'icon')),{position:groupExists?'never':'managed'});if(groupExists)moveShapeToPage(ids.icon,iconX,iconY);childIds.push(ids.icon);foreground.push(ids.icon)}
  const labelX=hasVisual?cardBounds.x+78:cardBounds.x+18,labelY=cardBounds.y+19,labelW=cardBounds.w-(hasVisual?96:36),labelAlign=hasVisual?'start':'middle'
  upsert(text(ids.label,labelX,labelY,labelW,node.label,'m',labelAlign,managed(prefix+'label',node.id,'label'),'black'),{position:groupExists?'never':'managed'});if(groupExists)moveShapeToPage(ids.label,labelX,labelY);childIds.push(ids.label);foreground.push(ids.label)
 }else{
  if(node.iconTileAssetId){upsert(image(ids.tile,node.x+22,node.y+28,78,78,AssetRecordType.createId(node.iconTileAssetId),node.label+' icon background',0,managed(prefix+'tile',node.id,'icon-tile')),{position:groupExists?'never':'managed'});childIds.push(ids.tile);foreground.push(ids.tile)}
  if(node.iconAssetId){upsert(image(ids.icon,node.x+22,node.y+28,78,78,AssetRecordType.createId(node.iconAssetId),node.label+' SLDS icon',0,managed(prefix+'icon',node.id,'icon')),{position:groupExists?'never':'managed'});childIds.push(ids.icon);foreground.push(ids.icon)}
  upsert(text(ids.label,node.x+116,node.y+34,node.w-136,node.label,'m','start',managed(prefix+'label',node.id,'label')),{position:groupExists?'never':'managed'});childIds.push(ids.label);foreground.push(ids.label)
 }
 if(node.apiName){upsert(text(ids.api,node.x+116,node.y+88,node.w-136,'('+node.apiName+')','s','start',managed(prefix+'api',node.id,'api')),{position:groupExists?'never':'managed'});childIds.push(ids.api);foreground.push(ids.api)}
 if(node.subtitle){upsert(text(ids.subtitle,node.x+116,node.y+94,node.w-136,node.subtitle,'s','start',managed(prefix+'subtitle',node.id,'subtitle')),{position:groupExists?'never':'managed'});childIds.push(ids.subtitle);foreground.push(ids.subtitle)}
 if(node.keyFields?.length){upsert(text(ids.keys,node.x+116,node.y+144,node.w-136,node.keyFields.join(' · '),'s','start',managed(prefix+'keys',node.id,'keys')),{position:groupExists?'never':'managed'});childIds.push(ids.keys);foreground.push(ids.keys)}
 if(node.boundary){upsert(geo(ids.boundary,node.x+node.w-132,node.y-17,120,34,'grey','solid','solid',node.boundary,managed(prefix+'boundary',node.id,'boundary',{lintIgnore:['overlapping-text','growY-on-shape']})),{position:groupExists?'never':'managed'});childIds.push(ids.boundary);foreground.push(ids.boundary)}
 for(let i=0;i<(node.observations?.length??0);i++){const value=node.observations[i],isLdv=value.startsWith('LDV'),w=Math.min(230,Math.max(116,value.length*8+28)),x=isLdv?node.x+node.w-w-10:node.x+(node.w-w)/2,y=isLdv?node.y-18:node.y+node.h-18,id=sid(prefix+'observation:'+i);upsert(geo(id,x,y,w,36,isLdv?'orange':'blue','solid','solid',value,managed(prefix+'observation:'+i,node.id,'observation',{lintIgnore:['overlapping-text','growY-on-shape']})),{position:groupExists?'never':'managed'});childIds.push(id);foreground.push(id)}
 if(groupExists){const cardBounds=editor.getShapePageBounds(ids.card),ungrouped=childIds.filter(id=>editor.getShape(id)?.parentId!==ids.group);if(ungrouped.length){if(FAMILY!=='sequence')helpers.translateShapes(ungrouped,cardBounds.x-node.x,cardBounds.y-node.y);editor.reparentShapes(ungrouped,ids.group)}}
 if(node.apiName){const label=editor.getShape(ids.label),api=editor.getShape(ids.api),labelBounds=editor.getShapePageBounds(label.id),apiBounds=editor.getShapePageBounds(api.id);const dy=labelBounds.maxY+8-apiBounds.y;if(Math.abs(dy)>0.01)helpers.translateShapes([api.id],0,dy)}
 if(node.subtitle){const label=editor.getShape(ids.label),subtitle=editor.getShape(ids.subtitle),labelBounds=editor.getShapePageBounds(label.id),subtitleBounds=editor.getShapePageBounds(subtitle.id);const dy=labelBounds.maxY+10-subtitleBounds.y;if(Math.abs(dy)>0.01)helpers.translateShapes([subtitle.id],0,dy)}
 if(!groupExists){const present=childIds.filter(id=>editor.getShape(id));if(present.length>1){editor.groupShapes(present,{groupId:ids.group,select:false});counters.created++;editor.updateShape({id:ids.group,type:'group',meta:managed(prefix+'group',node.id,'group')})}}
 else if(payload.renderMode==='relayout'){const bounds=editor.getShapePageBounds(ids.group);helpers.translateShapes([ids.group],node.x-bounds.x,node.y-bounds.y)}
 nodeGroups.set(node.id,ids.group)
}
const arrowIds=[],lifelineIds=[],activationForeground=[],labelBackgrounds=[],edgeForeground=[],markerChecks=[],bindingChecks=[],sequenceGeometryChecks=[]
function bindingsMatch(arrow,fromId,toId){const bindings=editor.getBindingsFromShape(arrow.id,'arrow'),start=bindings.find(binding=>binding.props.terminal==='start'),end=bindings.find(binding=>binding.props.terminal==='end');return start?.toId===fromId&&end?.toId===toId}
function arrowFor(edge,fromId,toId){const key='edge:'+edge.id+':arrow';let arrow=editor.getCurrentPageShapes().find(shape=>shape.type==='arrow'&&keyOf(shape)===key);if(arrow&&!bindingsMatch(arrow,fromId,toId)){editor.deleteShapes([arrow.id]);counters.deleted++;arrow=null}if(!arrow){const id=helpers.createArrowBetweenShapes(fromId,toId,{arrowheadStart:'none',arrowheadEnd:FAMILY==='data_model'?'none':'arrow',richText:toRichText('')});arrow=editor.getShape(id);counters.created++}const dash=FAMILY==='data_model'?'solid':edge.meaning==='response'||edge.meaning==='async_or_batch'?'dashed':edge.meaning==='async'||edge.meaning==='dependency'?'dotted':'solid';editor.updateShape({id:arrow.id,type:'arrow',meta:managed(key,edge.id,'arrow',{sfRelationId:edge.id,sfFrom:edge.from,sfTo:edge.to}),props:{kind:'arc',bend:0,color:'grey',dash,size:FAMILY==='sequence'?'m':'s',font:'sans',arrowheadStart:'none',arrowheadEnd:FAMILY==='data_model'?'none':'arrow',richText:toRichText('')}});counters.updated++;const updated=editor.getShape(arrow.id);bindingChecks.push({id:edge.id,valid:bindingsMatch(updated,fromId,toId)});return updated}
function midpoint(arrow,info){const tx=editor.getShapePageTransform(arrow.id);if(info.middle)return tx.applyToPoint(info.middle);return{x:(tx.applyToPoint(info.start.point).x+tx.applyToPoint(info.end.point).x)/2,y:(tx.applyToPoint(info.start.point).y+tx.applyToPoint(info.end.point).y)/2}}
function placeFromLocalAnchor(target,anchor,angle){const c=Math.cos(angle),s=Math.sin(angle);return{x:target.x-(anchor.x*c-anchor.y*s),y:target.y-(anchor.x*s+anchor.y*c)}}
function ensureMarker(edge,role,assetId,target,angle){const asset=payload.assets.find(item=>item.id===assetId),anchor=asset.anchor,id=sid('edge:'+edge.id+':'+role),position=placeFromLocalAnchor(target,anchor,angle),shape=image(id,position.x,position.y,asset.width,asset.height,AssetRecordType.createId(asset.id),role,angle,managed('edge:'+edge.id+':'+role,edge.id,role));upsert(shape,{position:'always'});const transform=editor.getShapePageTransform(id),actual=transform.applyToPoint(anchor),body=transform.applyToPoint({x:0,y:anchor.y});edgeForeground.push(id);return{delta:Math.hypot(actual.x-target.x,actual.y-target.y),body:{x:body.x-actual.x,y:body.y-actual.y}}}
function labelWidth(label){return Math.min(260,Math.max(62,label.length*9+28))}
function sequenceMessageWidth(label,span){const preferred=Math.max(190,label.length*7.5+72),available=Math.max(180,span-72);return Math.min(560,preferred,available)}
if(FAMILY==='sequence'){
 const interactionRows=payload.sequenceInteractions??[],rawFirst=Math.min(...interactionRows.map(item=>item.y)),participantBottom=Math.max(...payload.nodes.map(node=>editor.getShapePageBounds(cardBackgrounds.get(node.id)).maxY)),sequenceYOffset=Math.max(0,participantBottom+110-rawFirst),sequenceY=value=>value+sequenceYOffset,bottom=Math.max(760,...interactionRows.map(item=>sequenceY(item.y)))+120
 for(const node of payload.nodes){const cardId=cardBackgrounds.get(node.id),cardBounds=editor.getShapePageBounds(cardId),id=sid('node:'+node.id+':lifeline');upsert(geo(id,cardBounds.center.x-1,cardBounds.maxY,2,Math.max(80,bottom-cardBounds.maxY),'grey','solid','dashed','',managed('node:'+node.id+':lifeline',node.id,'lifeline')),{position:'always'});const lineBounds=editor.getShapePageBounds(id),labelBounds=editor.getShapePageBounds(sid('node:'+node.id+':label')),labelOverflow=Math.max(0,cardBounds.x+12-labelBounds.x)+Math.max(0,labelBounds.maxX-(cardBounds.maxX-12))+Math.max(0,cardBounds.y+12-labelBounds.y)+Math.max(0,labelBounds.maxY-(cardBounds.maxY-12));sequenceGeometryChecks.push({id:'lifeline:'+node.id,delta:Math.abs(lineBounds.center.x-cardBounds.center.x)+Math.abs(lineBounds.y-cardBounds.maxY)});sequenceGeometryChecks.push({id:'participant-label:'+node.id,delta:labelOverflow});lifelineIds.push(id)}
 const laneBounds=payload.nodes.map(node=>({id:node.id,bounds:editor.getShapePageBounds(cardBackgrounds.get(node.id))})).sort((left,right)=>left.bounds.x-right.bounds.x);for(let i=1;i<laneBounds.length;i++){const previous=laneBounds[i-1],current=laneBounds[i],shortfall=Math.max(0,previous.bounds.maxX+40-current.bounds.x);sequenceGeometryChecks.push({id:'lane-gap:'+previous.id+':'+current.id,delta:shortfall})}
 for(const activation of payload.sequenceActivations??[]){const cardId=cardBackgrounds.get(activation.participantId),cardBounds=editor.getShapePageBounds(cardId),id=sid('node:'+activation.participantId+':activation:'+activation.id),activationY=sequenceY(activation.y);upsert(geo(id,cardBounds.center.x-9,activationY,18,activation.h,'grey','semi','solid','',managed('node:'+activation.participantId+':activation:'+activation.id,activation.id,'sequence-activation')),{position:'always'});const bounds=editor.getShapePageBounds(id);sequenceGeometryChecks.push({id:'activation:'+activation.id,delta:Math.abs(bounds.center.x-cardBounds.center.x)+Math.abs(bounds.y-activationY)+Math.abs(bounds.h-activation.h)});activationForeground.push(id)}
 const sequenceActivationAt=(participantId,row)=>(payload.sequenceActivations??[]).some(activation=>activation.participantId===participantId&&sequenceY(activation.y)<=row&&row<=sequenceY(activation.y)+activation.h),sequenceAnchorX=(participantId,centerX,otherX,row)=>sequenceActivationAt(participantId,row)?centerX+(otherX>centerX?9:-9):centerX
 let previousMessageLabelBounds=null
 for(const edge of interactionRows){const edgeY=sequenceY(edge.y),fromCard=cardBackgrounds.get(edge.from),toCard=cardBackgrounds.get(edge.to),fromBounds=editor.getShapePageBounds(fromCard),toBounds=editor.getShapePageBounds(toCard),fromAnchor=sid('edge:'+edge.id+':from-anchor'),toAnchor=sid('edge:'+edge.id+':to-anchor'),fromX=sequenceAnchorX(edge.from,fromBounds.center.x,toBounds.center.x,edgeY),toX=sequenceAnchorX(edge.to,toBounds.center.x,fromBounds.center.x,edgeY);upsert(geo(fromAnchor,fromX-3,edgeY-3,6,6,'grey','none','none','',managed('edge:'+edge.id+':from-anchor',edge.id,'anchor',{lintIgnore:['tiny-shape']})),{position:'always'});upsert(geo(toAnchor,toX-3,edgeY-3,6,6,'grey','none','none','',managed('edge:'+edge.id+':to-anchor',edge.id,'anchor',{lintIgnore:['tiny-shape']})),{position:'always'});const a=editor.getShapePageBounds(fromAnchor).center,b=editor.getShapePageBounds(toAnchor).center;sequenceGeometryChecks.push({id:'anchors:'+edge.id,delta:Math.abs(a.x-fromX)+Math.abs(b.x-toX)+Math.abs(a.y-edgeY)+Math.abs(b.y-edgeY)});const arrow=arrowFor(edge,fromAnchor,toAnchor);arrowIds.push(arrow.id);const numbered=String(edge.step).padStart(2,'0')+'  '+edge.label,w=sequenceMessageWidth(numbered,Math.abs(b.x-a.x)),id=sid('edge:'+edge.id+':label');upsert(text(id,(a.x+b.x)/2-w/2,edgeY-74,w,numbered,'m','middle',managed('edge:'+edge.id+':label',edge.id,'label'),'black'),{position:'always'});const labelBounds=editor.getShapePageBounds(id),backgroundId=sid('edge:'+edge.id+':label-bg');upsert(geo(backgroundId,labelBounds.x-8,labelBounds.y-4,labelBounds.w+16,labelBounds.h+8,'white','solid','solid','',managed('edge:'+edge.id+':label-bg',edge.id,'message-label-background',{lintIgnore:['overlapping-text']})),{position:'always'});const backgroundBounds=editor.getShapePageBounds(backgroundId),minX=Math.min(a.x,b.x)+12,maxX=Math.max(a.x,b.x)-12,labelOverflow=Math.max(0,minX-labelBounds.x)+Math.max(0,labelBounds.maxX-maxX)+Math.max(0,labelBounds.maxY-(edgeY-8))+Math.max(0,labelBounds.h-64),rowOverlap=previousMessageLabelBounds?Math.max(0,previousMessageLabelBounds.maxY+16-labelBounds.y):0,backgroundOverflow=Math.max(0,backgroundBounds.x-labelBounds.x)+Math.max(0,labelBounds.maxX-backgroundBounds.maxX)+Math.max(0,backgroundBounds.y-labelBounds.y)+Math.max(0,labelBounds.maxY-backgroundBounds.maxY);sequenceGeometryChecks.push({id:'message-label:'+edge.id,delta:labelOverflow});sequenceGeometryChecks.push({id:'message-backing:'+edge.id,delta:backgroundOverflow});sequenceGeometryChecks.push({id:'message-row:'+edge.id,delta:rowOverlap});previousMessageLabelBounds=labelBounds;labelBackgrounds.push(backgroundId);edgeForeground.push(id)}
}else{
 for(const edge of payload.edges){const fromId=cardBackgrounds.get(edge.from),toId=cardBackgrounds.get(edge.to);if(!fromId||!toId)continue;const arrow=arrowFor(edge,fromId,toId);arrowIds.push(arrow.id);const info=getArrowInfo(editor,arrow);if(!info)throw new Error('No connector geometry for '+edge.id);const tx=editor.getShapePageTransform(arrow.id),middle=midpoint(arrow,info),w=labelWidth(edge.label),labelId=sid('edge:'+edge.id+':label');upsert(geo(labelId,middle.x-w/2,middle.y-20,w,40,'blue','solid','solid',edge.label,managed('edge:'+edge.id+':label',edge.id,'label',{lintIgnore:['overlapping-text','growY-on-shape']})),{position:'always'});edgeForeground.push(labelId)
  if(FAMILY==='data_model'){const start=tx.applyToPoint(info.start.point),end=tx.applyToPoint(info.end.point),sv={x:info.start.point.x-info.start.handle.x,y:info.start.point.y-info.start.handle.y},ev={x:info.end.handle.x-info.end.point.x,y:info.end.handle.y-info.end.point.y},sa=Math.atan2(sv.y,sv.x)+Math.PI,ea=Math.atan2(ev.y,ev.x),fromMarker=ensureMarker(edge,'from-marker',edge.fromMarkerAssetId,start,sa),toMarker=ensureMarker(edge,'to-marker',edge.toMarkerAssetId,end,ea),fromOrientation=fromMarker.body.x*sv.x+fromMarker.body.y*sv.y,toOrientation=toMarker.body.x*(-ev.x)+toMarker.body.y*(-ev.y);markerChecks.push({id:edge.id,fromDelta:fromMarker.delta,toDelta:toMarker.delta,fromOrientation,toOrientation})}
 }
}
if(arrowIds.length)editor.sendToBack(arrowIds)
if(lifelineIds.length)editor.sendToBack(lifelineIds)
if(foreground.length)editor.bringToFront(foreground)
if(activationForeground.length)editor.bringToFront(activationForeground)
if(labelBackgrounds.length)editor.bringToFront(labelBackgrounds)
if(edgeForeground.length)editor.bringToFront(edgeForeground)
function intersectingBounds(a,b){const x=Math.max(a.x,b.x),y=Math.max(a.y,b.y),maxX=Math.min(a.maxX,b.maxX),maxY=Math.min(a.maxY,b.maxY);return maxX>x&&maxY>y?{x,y,maxX,maxY}:null}
function containsBounds(outer,inner){return outer.x<=inner.x&&outer.y<=inner.y&&outer.maxX>=inner.maxX&&outer.maxY>=inner.maxY}
if(FAMILY==='sequence'){
 const shapeIndex=new Map(editor.getCurrentPageShapes().map(shape=>[shape.id,shape.index])),isAbove=(frontId,backId)=>String(shapeIndex.get(frontId)??'')>String(shapeIndex.get(backId)??'')
 for(const edge of payload.sequenceInteractions??[]){const labelId=sid('edge:'+edge.id+':label'),backgroundId=sid('edge:'+edge.id+':label-bg'),labelBounds=editor.getShapePageBounds(labelId),backgroundBounds=editor.getShapePageBounds(backgroundId);sequenceGeometryChecks.push({id:'message-layer:'+edge.id,delta:isAbove(labelId,backgroundId)?0:2});for(const node of payload.nodes){const lifelineId=sid('node:'+node.id+':lifeline'),intersection=intersectingBounds(labelBounds,editor.getShapePageBounds(lifelineId));if(intersection){const masked=containsBounds(backgroundBounds,intersection)&&isAbove(backgroundId,lifelineId)&&isAbove(labelId,backgroundId);sequenceGeometryChecks.push({id:'message-lifeline:'+edge.id+':'+node.id,delta:masked?0:2})}}for(const activation of payload.sequenceActivations??[]){const activationId=sid('node:'+activation.participantId+':activation:'+activation.id),intersection=intersectingBounds(labelBounds,editor.getShapePageBounds(activationId));if(intersection){const masked=containsBounds(backgroundBounds,intersection)&&isAbove(backgroundId,activationId)&&isAbove(labelId,backgroundId);sequenceGeometryChecks.push({id:'message-activation:'+edge.id+':'+activation.id,delta:masked?0:2})}}}
}
const typographyChecks=[]
if(FAMILY==='data_model'){for(const node of payload.nodes){const label=editor.getShape(sid('node:'+node.id+':label')),api=editor.getShape(sid('node:'+node.id+':api'));if(label&&api){const lb=editor.getShapePageBounds(label.id),ab=editor.getShapePageBounds(api.id),apiText=helpers.richTextToPlainText(api.props.richText).trim();typographyChecks.push({id:node.id,apiGap:Math.round((ab.y-lb.maxY)*100)/100,formatValid:/^\\([^()]+\\)$/.test(apiText)&&!/^\\(API\\s/i.test(apiText)})}}}
editor.selectNone()
editor.zoomToFit({animation:{duration:180}})
const lints=helpers.getLints().lints
const blockers=[]
if(lints.length)blockers.push({code:'canvas_lints',message:lints.map(lint=>lint.message).join('; ')})
if(bindingChecks.some(check=>!check.valid))blockers.push({code:'semantic_binding_mismatch',message:'One or more semantic connectors are bound to the wrong managed endpoints.'})
if(sequenceGeometryChecks.some(check=>check.delta>1))blockers.push({code:'sequence_geometry_mismatch',message:'One or more sequence lanes, activations, anchors, or labels violate the deterministic profile geometry.'})
if(markerChecks.some(check=>check.fromDelta>1||check.toDelta>1))blockers.push({code:'marker_terminal_mismatch',message:'One or more cardinality markers are not attached to actual connector terminals.'})
if(markerChecks.some(check=>check.fromOrientation<=0||check.toOrientation<=0))blockers.push({code:'marker_orientation_mismatch',message:'One or more cardinality markers point into a card instead of outward along the relationship.'})
if(typographyChecks.some(check=>Math.abs(check.apiGap-8)>0.5))blockers.push({code:'api_typography_gap',message:'One or more API names are not eight canvas units below the logical label.'})
if(typographyChecks.some(check=>!check.formatValid))blockers.push({code:'api_typography_format',message:'One or more API names are not parenthesized or include a forbidden API prefix.'})
const errorText=editor.getCurrentPageShapes().filter(shape=>shape.type==='text').some(shape=>helpers.richTextToPlainText(shape.props.richText).trim()==='Error')
if(errorText)blockers.push({code:'renderer_error_text',message:'Renderer fallback Error text is present.'})
return{documentId:null,pageId,pageName:editor.getCurrentPage().name,family:FAMILY,createdShapes:counters.created,updatedShapes:counters.updated,deletedShapes:counters.deleted,readiness:{ready:blockers.length===0,blockers,warnings:payload.warnings,lintCount:lints.length,markerChecks,bindingChecks,sequenceGeometryChecks,typographyChecks},lints}
`;
}
